name: build-with-openmpi
run-name: Build MPLR with OpenMPI
on: [push, pull_request, workflow_dispatch]
jobs:
  compile-mplr:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt install libopenmpi-dev cmake ninja-build g++ libboost-test-dev
          ompi_info
      - name: Build mplr
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_INSTALL_PREFIX="$HOME/mplr" -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DMPLR_BUILD_EXAMPLES=ON ..
          cmake --build . -j
          cmake --build . --target install
      - name: Test mplr
        run: |
          cd build
          ctest --output-on-failure
      - run: echo "This job's status is ${{ job.status }}."
